<?php
	$title = 'User Login';
	$this->headTitle ( $title );
?>
<div class="login_wrapper">
	<h3><?php echo $this->escapeHtml($title); ?></h3>
	<?php
		$loginForm = $this->loginForm;
		$loginForm->setAttribute ( 'action', $this->url ( 'base', array ('controller'=>'index','action' => 'login' ) )  );
		$loginForm->prepare ();
		echo $this->form ()->openTag ( $loginForm );
	?>
	<table>
		<tr>
			<td><?php echo $this->formRow($loginForm->get('username')); ?></td>
		</tr>
		<tr>
			<td><?php echo $this->formRow($loginForm->get('password')); ?></td>
		</tr>
		<tr>
			<td colspan="2" align="center"><?php echo $this->formSubmit($loginForm->get('submit')); ?></td>
		</tr>
	</table>
	<?php
		echo $this->form ()->closeTag ();
	?>
</div>
<div class="signup_wrapper">
	<h3><?php echo $this->escapeHtml('Sign Up Form'); ?></h3>
	<?php
		$signUpForm = $this->signUpForm;
		$signUpForm->setAttribute ( 'action', $this->url ( 'base', array ('controller'=>'index','action' => 'login' ) ) );
		$signUpForm->prepare ();
		echo $this->form ()->openTag ( $signUpForm ); ?>
	<table>
		<tr>
			<td><?php echo $this->formRow($signUpForm->get('fullname')); ?></td>
		</tr>
		<tr>
			<td><?php echo $this->formRow($signUpForm->get('emailid')); ?></td>
		</tr>
		<tr>
			<td><?php echo $this->formRow($signUpForm->get('username')); ?></td>
		</tr>
		<tr>
			<td><?php echo $this->formRow($signUpForm->get('password')); ?></td>
		</tr>
		<tr>
			<td colspan="2" align="center"><?php echo $this->formSubmit($signUpForm->get('submit')); ?></td>
		</tr>
	</table>
	<?php
		echo $this->form ()->closeTag ();
	?>
</div>