<script src="../js/ckeditor/ckeditor.js"></script>
<?php

    $title = 'Status Form';
    $this->headTitle ( $title );
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<?php
    $statusForm = $this->statusForm;
    $statusForm->setAttribute ( 'action', $this->url ( 'base', array ('controller'=>'status','action' => 'saveStatus' )));
    $statusForm->prepare ();
    echo $this->form ()->openTag ( $statusForm );
?>
<?php echo $this->formRow($statusForm->get('ticketno')); 
 echo $this->formRow($statusForm->get('title')); 
 echo $this->formRow($statusForm->get('description'));
 echo $this->formSubmit($statusForm->get('submit'));
    echo $this->form ()->closeTag ();
?>
<script type="text/javascript">
$(document).ready(function(){
	CKEDITOR.replace( 'description' );
	});

</script>