<script src="../js/ckeditor/ckeditor.js"></script>
<?php

    $title = 'Status Form';
    $this->headTitle ( $title );
?>
<div class="status_wrapper">
 <div class="sign_title"><?php echo $this->escapeHtml('Fill up your Status'); ?></div>


<?php
    $statusForm = $this->statusForm;
    $statusForm->setAttribute ( 'action', $this->url ( 'base', array ('controller'=>'status','action' => 'index' )));
    $statusForm->prepare ();
    echo $this->form ()->openTag ( $statusForm );
?>
 <div class="content">
<?php
echo $this->formRow($statusForm->get('ticketType'))." - ";
echo $this->formRow($statusForm->get('ticketNumber'));
echo $this->formRow($statusForm->get('title'));
echo $this->formRow($statusForm->get('status'));
echo $this->formRow($statusForm->get('description'));
echo $this->formSubmit($statusForm->get('submit'));
echo $this->form ()->closeTag ();
?>
</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	CKEDITOR.replace( 'description' );
	});

</script>