<?php
if ($this->reportObj) {
	$reportObj = $this->reportObj;
}

?>

<div class="report_container">
<?php
if (! empty ( $reportObj ))
{
	unset($reportObj->userId);
	unset($reportObj->name);
	foreach ( $reportObj as $reportDate => $reports )
	{
		?>
		<div class="viewBlock">		
			<h4><?php echo date('jS F Y', strtotime($reportDate)) ?></h4>
		<?php
			$reportNo = 1;
			foreach ( $reports->report as $report ) 
			{
		?>
		<dl class="dl-horizontal dl-cust">
		 <dt> <?php echo $reportNo ?>. <a href="http://jira.theorchard.com/browse/<?php echo $report->jiraTicketId ?>"target="_blank"><?php echo $report->jiraTicketId ?></a> </dt>
		 <dd><?php echo $report->title?></dd>
		 <dt>Status</dt>
		 <dd><?php echo $report->status ?></dd>
		 <dt></dt>
		 <dd>
		 <div class="desc_cont">
		                <?php echo $report->description?>
		  </div>
		 </dd>
		</dl>
				
				
				
			<?php
			$reportNo++;
		}?>
		</div>
		<?php 
	}
}

?>
</div>
