<?php 
if($this->reports)
{
	$reports = $this->reports;
}

?>

<div class="report_container">
<?php 
	if(!empty($reports))
	{
		foreach ($reports as $report)
		{
			?>
			<h4><?php echo date('jS F Y', strtotime($report->dateAdded->date)) ?></h4>
			1. <a href="http://jira.theorchard.com/browse/<?php echo $report->ticketNo ?>" target="_blank"><?php echo $report->ticketNo ?></a> : 
			<?php echo $report->title ?>
			<span class="status_cont">Status : Under Review</span>
			<div class="desc_cont">
                <?php echo $report->description ?>
    		</div>
			<?php 
		}
	}

?>
</div>
