<div class="report_container">
	<div class="user_content">
<?php if(!empty($this->teamUser)){
	foreach ($this->teamUser as $user){
?>
	<div class="suser">
			<input onchange="javascript:getUserReport('<?php echo $user->userId ?>')" id="user<?php echo $user->userId ?>" type="checkbox" name="users" value="<?php echo $user->userId ?>"/>
			<label class="user_title" for="user<?php echo $user->userId ?>">
				<?php echo $user->firstName ?>
			</label>
	</div>
<?php }
}?>
	</div>
	<div id="report_content" class="report_content">

	</div>
	<div class="clear"></div>
</div>

<script>
function getUserReport(userId)
{
	if($('#user'+userId).is(':checked'))
	{
		var date = '<?php echo date('Y-m-d', strtotime("-6 hours",strtotime(date('Y-m-d H:i:s')))) ; ?>';
		 $.ajax({
	       	type:"POST",
	        url:"<?php echo $this->url('base', array('controller'=>'status','action'=>'getUserReport')) ?>",
	        data:{userId:userId, reportDate : date},
	        success: function(userReportObj){
		        if(userReportObj){
			        var userReportHtml = produceReportHtml(userReportObj);
		          	$("#report_content").append(userReportHtml);
		        }
			}
		 });
	}
	else
	{
		$('#reportData'+userId).remove();
	}
}

function produceReportHtml(userReportObj)
{
	var reportHtml = '';
	$.each(userReportObj, function(index, userReport){
		$.each(userReport, function(key, report){
			reportHtml += '<div id="reportData'+report.userId+'" class="report_data">';
			reportHtml += '<h4>'+report.name+'</h4>';
			var reportNo = 1;
			$.each(report.report, function(key, r){
					reportHtml += '<div class="report">';
					reportHtml += reportNo + '. <a href="http://jira.theorchard.com/browse/'+r.jiraTicketId+'" target="_blank"> '+r.jiraTicketId+'</a> : ';
					reportHtml += r.title;
					reportHtml += '<span class="status_cont">Status : '+r.status+'</span>';
					reportHtml += '<div class="desc_cont">'+r.description;
					reportHtml += '</div></div>';
					reportNo ++;
			});
			reportHtml += '</div>';
		});
	});
	return reportHtml;
}

</script>