<div class="report_container">

	<div class="user_content">
<?php if(!empty($this->teamUser)){
	foreach ($this->teamUser as $user){
?>
	<div class="suser">
			<input onchange="javascript:getUserReport('<?php echo $user->userId ?>')" id="user<?php echo $user->userId ?>" type="checkbox" name="users" value="<?php echo $user->userId ?>"/>
			<label class="user_title" for="user<?php echo $user->userId ?>">
				<?php echo $user->firstName ?>
			</label>
	</div>
<?php }
}?>
	</div>
	<div id="report_content" class="report_content">
	<div class="report_filter" id="report_filter">
		<input type="radio" name ="report_filter" value="1" id="days1"/>
		<label id="lbl1" class="report-filter-label filter-img" for="days1">Today</label> 
		<input type="radio" name ="report_filter" value="7" id="days7"/>
		<label id="lbl7" class="report-filter-label filter-img" for="days7">7 Days</label> 
		<input type="radio" name ="report_filter" value="15" id="days15"/>
		<label id="lbl15" class="report-filter-label filter-img" for="days15">15 Days</label> 
		<input type="radio" name ="report_filter" value="30" id="days30"/>
		<label id="lbl30" class="report-filter-label filter-img" for="days30">30 Days</label> 
</div>
	<div id="report_body" class="report_body">
	
	</div>
	</div>
	<div class="clear"></div>
</div>

<script>
var dateRange = 1;
$(document).ready(function(){
	$("#report_filter input[type='radio']").click(function(){
		selectedId = $(this).val();
		dateRange = selectedId;
		setActiveLabelFilter(selectedId);
		getUserReport(userId);
	});
});

function setActiveLabelFilter(id)
{
	//$('.report-filter-label').addClass('filter-img');
	hassId = '#lbl'+id;
	$(hassId).removeClass('filter-img');
	$(hassId).addClass('active-filter');
}
function getUserReport(userId)
{
	if($('#user'+userId).is(':checked'))
	{
		var curDate = '<?php echo date('Y-m-d H:i:s', strtotime("+6 hours",strtotime(date('Y-m-d H:i:s')))) ; ?>';
		 $.ajax({
	       	type:"POST",
	        url:"<?php echo $this->url('base', array('controller'=>'status','action'=>'getUserReport')) ?>",
	        data:{userId : userId, curDate : curDate, dateRange : dateRange},
	        success: function(userReportObj){
		        if(userReportObj){
			        var userReportHtml = produceReportHtml(userReportObj);
		          	$("#report_body").append(userReportHtml);
		        }
			}
		 });
	}
	else
	{
		$('#reportData'+userId).remove();
	}
}

function produceReportHtml(userReportObj)
{
	var reportHtml = '';
	$.each(userReportObj, function(index, userReport){
		reportHtml += '<div id="reportData'+userReport.userId+'" class="viewBlock">';
		reportHtml += '<h4>';
		if(userReport.name){			
			reportHtml += userReport.name;
			delete userReport.name;
			delete userReport.userId;
		}
		reportHtml += '</h4>';
		$.each(userReport, function(key, report){	
			reportHtml += '<dl class="dl-horizontal dl-cust dl-style-1"><dt></dt><dd class="date">'+ key +'</dd>';
			var reportNo = 1;
			$.each(report.report, function(key, r){
					reportHtml += '<dt>';
					reportHtml += reportNo + '. <a href="http://jira.theorchard.com/browse/'+r.jiraTicketId+'" target="_blank"> '+r.jiraTicketId+'</a> : </dt><dd> ';
					reportHtml += r.title;
					reportHtml += '</dd><dt>Status : </dt><dd>'+r.status+'</dd><dt></dt>';
					reportHtml += '<dd>'+r.description;
					reportHtml += '</dd>';
					reportNo ++;
			});
			reportHtml += '</dl>';
		});
		reportHtml += '</div>';
	});
	return reportHtml;
}

</script>