<div class="report_container">
	<div class="user_content">
<?php if(!empty($this->teamUser)){
	foreach ($this->teamUser as $user){
?>
	<div class="suser">	
			<input onchange="javascript:getUserReport('<?php echo $user->userId ?>')" id="user<?php echo $user->userId ?>" type="checkbox" name="users" value="<?php echo $user->userId ?>"/>
			<label class="user_title" for="user<?php echo $user->userId ?>">
				<?php echo $user->firstName ?>	
			</label>
	</div>
<?php }
}?>
	</div>
	<div id="report_content" class="report_content">
		<div id="report_data1" class="report_data">
			<h4>Narendra Singh</h4>
				1. <a href="http://jira.theorchard.com/browse/ASC-455" target="_blank">ASC-455</a> : 
				Change Store Genre Spreadsheet Uploader rules
				<span class="status_cont">Status : Under Review</span>
				<div class="desc_cont">
	               The speadsheet uploader on this page should not reject files because they do not have all fields completed 
	               that are configured on the DMS page. They should allow those fields to be accepted, but some stores 
	               (Google for example) have just a genre or genre/sub-genre combinations that will need to be uploaded.
	    		</div>
		</div>
	</div>
	<div class="clear"></div>
</div>

<script>
function getUserReport(userId)
{
	if($('#user'+userId).is(':checked'))
	{
		var date = '<?php echo date('Y-m-d', strtotime("-6 hours",strtotime(date('Y-m-d H:i:s')))) ; ?>';
		 $.ajax({
	       	type:"POST",
	        url:"<?php echo $this->url('base', array('controller'=>'status','action'=>'getUserReport')) ?>",
	        data:{userId:userId, reportDate : date},
	        success: function(data){
		        if(data){
			        var userReportHtml = produceReportHtml(data);
		          	$("#report_content").append(userReportHtml);
		        }
			}
		 });
	}
	else
	{
		alert('unchecked');
	}
}

function produceReportHtml(data)
{
	var reportHtml = '<div id="report_data1" class="report_data">';
	
}

</script>