<div class="report_container">
	<div class="user_content">
		<div class="suser">	
			<input id="user1" type="checkbox" name="users" value="1"/>
			<label class="user_title" for="user1">
				Narendra	
			</label>
		</div>
		<div class="suser">	
			<input id="user2" type="checkbox" name="users" value="1"/>
			<label class="user_title" for="user2">
				Shreeya
			</label>
		</div>
		<div class="suser">	
			<input id="user3" type="checkbox" name="users" value="1"/>
			<label class="user_title" for="user3">
				Urvi	
			</label>
		</div>
		<div class="suser">	
			<input id="user4" type="checkbox" name="users" value="1"/>
			<label class="user_title" for="user4">
				Rakesh	
			</label>
		</div>
		<div class="suser">	
			<input id="user5" type="checkbox" name="users" value="1"/>
			<label class="user_title" for="user5">
				Sadhana	
			</label>
		</div>
		<div class="suser">	
			<input id="user6" type="checkbox" name="users" value="1"/>
			<label class="user_title" for="user6">
				Abhinandan	
			</label>
		</div>
		<div class="suser">	
			<input id="user7" type="checkbox" name="users" value="1"/>
			<label class="user_title" for="user7">
				Abhinav
			</label>
		</div>
	
	</div>
	<div class="report_content">
		<div class="report_data">
			<h4>Narendra Singh</h4>
				1. <a href="http://jira.theorchard.com/browse/ASC-455" target="_blank">ASC-455</a> : 
				Change Store Genre Spreadsheet Uploader rules
				<span class="status_cont">Status : Under Review</span>
				<div class="desc_cont">
	               The speadsheet uploader on this page should not reject files because they do not have all fields completed 
	               that are configured on the DMS page. They should allow those fields to be accepted, but some stores 
	               (Google for example) have just a genre or genre/sub-genre combinations that will need to be uploaded.
	    		</div>
		</div>
			<div class="report_data">
			<h4>Shreeya Rane</h4>
				1. <a href="http://jira.theorchard.com/browse/ASC-455" target="_blank">ASC-455</a> : 
				Change Store Genre Spreadsheet Uploader rules
				<span class="status_cont">Status : Under Review</span>
				<div class="desc_cont">
	               The speadsheet uploader on this page should not reject files because they do not have all fields completed 
	               that are configured on the DMS page. They should allow those fields to be accepted, but some stores 
	               (Google for example) have just a genre or genre/sub-genre combinations that will need to be uploaded.
	    		</div>
		</div>
			<div class="report_data">
			<h4>Mital Dadhania</h4>
				1. <a href="http://jira.theorchard.com/browse/ASC-455" target="_blank">ASC-455</a> : 
				Change Store Genre Spreadsheet Uploader rules
				<span class="status_cont">Status : Under Review</span>
				<div class="desc_cont">
	               The speadsheet uploader on this page should not reject files because they do not have all fields completed 
	               that are configured on the DMS page. They should allow those fields to be accepted, but some stores 
	               (Google for example) have just a genre or genre/sub-genre combinations that will need to be uploaded.
	    		</div>
		</div>
	</div>
	<div class="clear"></div>
</div>