<?php echo $this->doctype(); echo $this->action;die; ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php  echo $this->headTitle('Synergy - The Orchard '. $this->translate('Status Mail Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.min.js'); ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url('base') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php // echo $this->translate('Skeleton Application') ?></a>
                </div>
               <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php if(!empty($_SESSION['appl'])) { ?>
                        <?php if ($_SESSION['appl']['username']){ ?>
                        	<li <?php echo activeMenu('')?>><a href="<?php echo $this->url('base') ?>"><?php echo ($_SESSION['appl']['firstName'])." ".($_SESSION['appl']['lastName']); ?></a></li>
							<li <?php echo activeMenu(array('controller'=>'status','action'=>'index'))?>><a href="<?php echo $this->url('base', array('controller'=>'status','action'=>'index')) ?>">New Report</a></li>
							<li class="active"><a href="<?php echo $this->url('base', array('controller'=>'status','action'=>'report')) ?>">View Report</a></li>

						<?php }?>
           				<?php if($_SESSION['appl']['userType'] == 2 || $_SESSION['appl']['userType'] == 1 ){?>
           					<li class="active"><a href="<?php echo $this->url('base',array('controller'=>'status','action'=>'viewallreport')) ?>">View All Reports</a></li>
           				<?php }?>
                        <?php if($_SESSION['appl']['userType'] == 1){?>
                        	<li class="active"><a href="<?php echo $this->url('base', array('controller'=>'admin','action'=>'addteam')) ?>">Add Team</a></li>
							<li class="active"><a href="<?php echo $this->url('base', array('controller'=>'admin','action'=>'manageteam')) ?>">Manage Team</a></li>
                         <?php }?>
                         <?php if ($_SESSION['appl']['username']){?>
                         	<li class="active"><a href="<?php echo $this->url('base',array('controller'=>'login','action'=>'logout')) ?>">Logout</a></li><?php }?>
                         <?php } ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>

<?php 
function activeMenu($route)
{
	if($route['controller']=== $this->controller)
	{
		if()
	}
}

function route($route)
{
	
}
?>
