<?php echo $this->doctype();?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php  echo $this->headTitle('Synergy - The Orchard '. $this->translate('Status Mail Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.min.js'); ?>
    </head>
    <body>
    	<?php echo $this->partial('menu'); ?>
        <div class="main-wrapper">
        <div class="container">
            <?php echo $this->content; ?>
            
            <footer> </footer>
        </div> <!-- /container -->
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
