<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
     <div class="container">
               <div class="collapse navbar-collapse">
                  <?php if(!empty($activeMenu->controller)) {
                      if($activeMenu->controller != "pm") { ?>
                    <ul class="nav navbar-nav">
                        <?php
                        foreach ($userMenu->management as $controller => $menus) {
                            if($controller !=='error'){
                                $controllerMenu = array($controller, $menus);
                                processMenu($activeMenu, $controller, $menus, $this);
                            }
                         } ?>
                    </ul>
                    <?php } } else { ?>
                    <ul class="nav navbar-nav">
                        <li><a href="#home">Home</a></li>
                        <li><a href="#project">Project</a></li>
                        <li><a href="#changepassword">Change Password</a></li>
                        <li><a href="#userprofile">User Profile</a></li>
                    </ul>
                  <?php }?>
                </div>
            </div>
</nav>

<?php

/**
 *
 * @param object $activeUrl
 * @param string $controller
 * @param object $menus
 * @param object $that
 */
function processMenu($activeUrl, $controller, $menus, $that)
{
    foreach ($menus as $action => $description){
        $route = new \stdClass();
        $route->controller = $controller;
        $route->action = $action;
        $url = route($that, $route);
        $active = ($activeUrl->controller == $controller && $activeUrl->action == $action) ? 'active' :'';
        echo  "<li class='{$active}'><a href='{$url}'>{$description}</a></li>";
    }

}

/**
 *
 * @param object $that
 * @param object $route
 * @return string
 */
function route($that, $route)
{
	if(!empty($route)){
		return $that->url('base', array('controller'=>$route->controller,'action'=>$route->action));
	}else{
		return "";
	}
}