<?php
    $title = 'Add Team Member';
    $this->headTitle($title);
?>
<script type="text/javascript">
$(document).ready(function() {
	$('#add').click(function() {
		$("#msg").html("");
		if($('#TeamMember :selected').size()==0)
			$("#msg").html("Please select at least one employee");
		$('#SelectedTeamMember').append($('#TeamMember :selected'));
		$('#SelectedTeamMember :selected').each(function(i, selected){
			   $(selected).attr("selected",false);
			});
	});
	$('#remove').click(function() {
		$("#msg").html("");
		if($('#SelectedTeamMember :selected').size()==0)
			$("#msg").html("Please select at least one employee");
		$('#TeamMember').append($('#SelectedTeamMember :selected'));

	});
});

</script>
<div class="team_member">
    <div class="sign_title">
        <?php
            echo $this->escapeHtml($title);
        ?>
    </div>
     <?php
        $AddTeamMemberForm = $this->AddTeamMemberForm;
        $AddTeamMemberForm->prepare();
        echo $this->form()->openTag($AddTeamMemberForm);
    ?>
    <div class="content">
        <?php echo $this->formRow($AddTeamMemberForm->get('Team'));?>
        <hr>
      	<table>
	      	<tr>
	      		<td style="text-align:center;">Select Users</td>
	      		<th></th>
	      		<td style="text-align:center;">Selected Users</td>
	      	</tr>
	      	<tr>
	      		<td><?php echo $this->formRow($AddTeamMemberForm->get('TeamMember'));?></td>
	      		<td style="vertical-align: middle; text-align: center;">
		      		<input type="button" id="add" name="Add" value=">>" class='move'>
					<br>
					<input type="button" id="remove" name="Remove" value="&lt&lt" class='move' >
				</td>
	      		<td><?php  echo $this->formRow($AddTeamMemberForm->get('SelectedTeamMember')); ?></td>
	      	</tr>
         </table>
         <?php   echo $this->formSubmit($AddTeamMemberForm->get('submit'));?>
    </div>
    <?php
        echo $this->form()->closeTag();
    ?>
</div>