<!--<h3>Timesheet</h3>-->
<script src="<?php echo $this->basePath() ?>/js/backbone/libs/require.js" data-main="<?php echo $this->basePath() ?>/js/backbone/apps/app"></script>

<style>
#content
{
	margin-top: 15px;
}
.button
{
    background: #47C3F8;
    width:100px;
    padding: 5px;
    border-radius: 7px;
    text-align: center;
    cursor: pointer;
    color: #fefefe;
}
.button:hover
{
    background: #10ADF5;
}

</style>
<div id="content">

</div>